[target.wasm32v1-none]
# https://github.com/wasmi-labs/wasmi?tab=readme-ov-file#webassembly-proposals
rustflags = [
	"-Cpanic=abort",
	"-Ctarget-feature=+bulk-memory",
	"-Ctarget-feature=+multivalue",
	"-Ctarget-feature=+reference-types",
	"-Clto=fat",
	"-Cembed-bitcode",
]
